name: Build and Package ParserKrisha

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Установка необходимых зависимостей
        pip install requests beautifulsoup4 pyperclip
        # Установка PyInstaller и Pillow
        pip install pyinstaller Pillow

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=parser.ico parser_gui.py

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Inno Setup
      run: |
        choco install innosetup -y

    - name: Verify Inno Setup Installation
      run: |
        if (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe") {
            echo "Inno Setup is installed correctly."
        } else {
            echo "ISCC.exe not found at the specified path."
            exit 1
        }

    - name: Find ISCC.exe
      id: find_iscc
      run: |
        $iscc = Get-ChildItem -Path "C:\Program Files*" -Filter "ISCC.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($iscc) {
            Add-Content -Path $env:GITHUB_ENV -Value "ISCC_PATH=$($iscc.FullName)"
            echo "Found ISCC.exe at $($iscc.FullName)"
        } else {
            echo "ISCC.exe not found."
            exit 1
        }

    - name: Create Inno Setup Script
      run: |
        @"
        [Setup]
        AppName=Парсер Кришa
        AppVersion=1.0
        DefaultDirName={pf}\ПарсерКришa
        DefaultGroupName=Парсер Кришa
        OutputBaseFilename=ParserKrishaInstaller
        Compression=lzma
        SolidCompression=yes

        [Files]
        Source: "dist\parser_gui.exe"; DestDir: "{app}"; Flags: ignoreversion
        Source: "parser.ico"; DestDir: "{app}"; Flags: ignoreversion

        [Icons]
        Name: "{group}\Парсер Кришa"; Filename: "{app}\parser_gui.exe"; IconFilename: "{app}\parser.ico"
        Name: "{commondesktop}\Парсер Кришa"; Filename: "{app}\parser_gui.exe"; IconFilename: "{app}\parser.ico"; Tasks: desktopicon

        [Tasks]
        Name: "desktopicon"; Description: "Создать ярлык на рабочем столе"; Flags: checked

        [Run]
        Filename: "{app}\parser_gui.exe"; Description: "Запустить Парсер Кришa"; Flags: nowait, postinstall, skipifsilent
        "@ | Out-File -FilePath install_script.iss -Encoding utf8NoBOM

    - name: Show Inno Setup Script Content
      run: |
        Get-Content install_script.iss

    - name: Show ISCC_PATH
      run: |
        echo "ISCC_PATH=$env:ISCC_PATH"

    - name: Check ISCC.exe exists
      run: |
        if (!(Test-Path "$env:ISCC_PATH")) {
            Write-Error "ISCC.exe not found at $env:ISCC_PATH"
            exit 1
        } else {
            Write-Host "ISCC.exe exists at $env:ISCC_PATH"
        }

    - name: List Inno Setup Directory
      run: |
        Get-ChildItem "C:\Program Files (x86)\Inno Setup 6\"

    - name: Compile Inno Setup Script
      run: |
        Start-Process -FilePath "$env:ISCC_PATH" -ArgumentList "install_script.iss" -Wait -NoNewWindow

    - name: Upload Installers
      uses: actions/upload-artifact@v3
      with:
        name: Installers
        path: |
          dist/parser_gui.exe
          ParserKrishaInstaller.exe
