name: Build and Package ParserKrisha

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) {
            pip install -r requirements.txt
        } else {
            echo "No requirements.txt found"
        }
        pip install pyinstaller Pillow

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=parser.ico parser_gui.py

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Inno Setup
      run: |
        choco install innosetup -y

    - name: Verify Inno Setup Installation
      run: |
        if (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe") {
            echo "Inno Setup is installed correctly."
        } else {
            echo "ISCC.exe not found at the specified path."
            exit 1
        }

    - name: Create Inno Setup Script
      run: |
        Add-Content -Path install_script.iss -Value "[Setup]"
        Add-Content -Path install_script.iss -Value "AppName=Парсер Кришa"
        Add-Content -Path install_script.iss -Value "AppVersion=1.0"
        Add-Content -Path install_script.iss -Value "DefaultDirName={pf}\ПарсерКришa"
        Add-Content -Path install_script.iss -Value "DefaultGroupName=Парсер Кришa"
        Add-Content -Path install_script.iss -Value "OutputBaseFilename=ParserKrishaInstaller"
        Add-Content -Path install_script.iss -Value "Compression=lzma"
        Add-Content -Path install_script.iss -Value "SolidCompression=yes"
        Add-Content -Path install_script.iss -Value ""
        Add-Content -Path install_script.iss -Value "[Files]"
        Add-Content -Path install_script.iss -Value 'Source: "dist\parser_gui.exe"; DestDir: "{app}"; Flags: ignoreversion'
        Add-Content -Path install_script.iss -Value 'Source: "parser.ico"; DestDir: "{app}"; Flags: ignoreversion'
        Add-Content -Path install_script.iss -Value ""
        Add-Content -Path install_script.iss -Value "[Icons]"
        Add-Content -Path install_script.iss -Value 'Name: "{group}\Парсер Кришa"; Filename: "{app}\parser_gui.exe"; IconFilename: "{app}\parser.ico"'
        Add-Content -Path install_script.iss -Value 'Name: "{commondesktop}\Парсер Кришa"; Filename: "{app}\parser_gui.exe"; IconFilename: "{app}\parser.ico"; Tasks: desktopicon'
        Add-Content -Path install_script.iss -Value ""
        Add-Content -Path install_script.iss -Value "[Tasks]"
        Add-Content -Path install_script.iss -Value 'Name: "desktopicon"; Description: "Создать ярлык на рабочем столе"; GroupDescription: "Дополнительные ярлыки:"; Flags: checked'
        Add-Content -Path install_script.iss -Value ""
        Add-Content -Path install_script.iss -Value "[Run]"
        Add-Content -Path install_script.iss -Value 'Filename: "{app}\parser_gui.exe"; Description: "Запустить Парсер Кришa"; Flags: nowait postinstall skipifsilent'

    - name: Compile Inno Setup Script
      run: |
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" install_script.iss

    - name: Upload Installers
      uses: actions/upload-artifact@v3
      with:
        name: Installers
        path: |
          dist/parser_gui.exe
          ParserKrishaInstaller.exe
